# Generated by Django 2.2.2 on 2019-06-15 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('customer_type', models.IntegerField(blank=True, choices=[(1, 'CustomerType.CUSTOMER_TYPE_PERSON'), (2, 'CustomerType.CUSTOMER_TYPE_COMPANY')], null=True)),
                ('customer_document', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('contract_type', models.IntegerField(blank=True, choices=[(1, 'ConstractType.CONTRACT_TYPE_CTPS'), (2, 'ConstractType.CONTRACT_TYPE_CNPJ')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer: Customer',
            },
        ),
    ]
