# Generated by Django 2.2.2 on 2019-06-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20190622_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstencepermission',
            name='name',
        ),
    ]
